FROM node:20-alpine

WORKDIR /app

# Define build arguments
ARG PORT
ARG MONGODB_URI
ARG JWT_SECRET
ARG JWT_REFRESH_SECRET
ARG JWT_TOKEN_EXPIRY_MINUTES
ARG JWT_REFRESH_TOKEN_EXPIRY_MINUTES
ARG USER_EMAIL
ARG EMAIL_APP_PASSWORD
ARG COMPILER_URL
ARG FRONTEND_URL
ARG ADMIN_URL
ARG CLOUDINARY_URL

# Set environment variables from build arguments
ENV PORT=${PORT}
ENV MONGODB_URI=${MONGODB_URI}
ENV JWT_SECRET=${JWT_SECRET}
ENV JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
ENV JWT_TOKEN_EXPIRY_MINUTES=${JWT_TOKEN_EXPIRY_MINUTES}
ENV JWT_REFRESH_TOKEN_EXPIRY_MINUTES=${JWT_REFRESH_TOKEN_EXPIRY_MINUTES}
ENV USER_EMAIL=${USER_EMAIL}
ENV EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
ENV COMPILER_URL=${COMPILER_URL}
ENV FRONTEND_URL=${FRONTEND_URL}
ENV ADMIN_URL=${ADMIN_URL}
ENV CLOUDINARY_URL=${CLOUDINARY_URL}

COPY . .
# Copy package files and install production dependencies only
COPY package*.json ./
RUN npm install 

# Copy built files from builder stage
RUN npm run build

# Expose the port
EXPOSE 4000

# Start the application
CMD ["npm","run","start"]